version: "3.7"

services:
  client_db:
    build:
      context: ./client
      dockerfile: ./resources/docker/db.dockerfile
    environment:
      POSTGRES_DB: event
      POSTGRES_USER: event
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  product_db:
    build:
      context: ./product
      dockerfile: ./resources/docker/db.dockerfile
    environment:
      POSTGRES_DB: event
      POSTGRES_USER: event
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  order_db:
    build:
      context: ./order
      dockerfile: ./resources/docker/db.dockerfile
    environment:
      POSTGRES_DB: event
      POSTGRES_USER: event
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  bus:
    build:
      context: ./bus
      dockerfile: ./resources/docker/app.dockerfile
    restart: on-failure

  client:
    build:
      context: ./client
      dockerfile: ./resources/docker/app.dockerfile
    depends_on:
      - client_db
    environment:
      DATABASE_URL: postgres://event:123456@client_db/event?sslmode=disable
    restart: on-failure

  product:
    build:
      context: ./product
      dockerfile: ./resources/docker/app.dockerfile
    depends_on:
      - product_db
    environment:
      DATABASE_URL: postgres://event:123456@product_db/event?sslmode=disable
    restart: on-failure

  order:
    build:
      context: ./order
      dockerfile: ./resources/docker/app.dockerfile
    depends_on:
      - order_db
    environment:
      DATABASE_URL: postgres://event:123456@order_db/event?sslmode=disable
    restart: on-failure

